//
//  Azot.h
//  Azot
//
//  Created by Thomas Carayol on 16/01/15.
//  Copyright (c) 2015 Appstud. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface Azot : NSObject

#define AZLOG(__FORMAT__, ...) AZLog((@"%s line %d $ " __FORMAT__), __PRETTY_FUNCTION__, __LINE__, ##__VA_ARGS__)

typedef NS_ENUM(int, AZConfidentiality) {
    AZConfidentialityLow = 0,
    AZConfidentialityMedium,
    AZConfidentialityHigh
} NS_AVAILABLE_IOS(7_0);

/**
 *  Start analysis in the app. Call it in your app delegate.
 *  @param azotAppToken is the token generated by Azot for the developer to track his app
 *  @return void
 */
+ (void)start:(NSString*)azotAppToken;

/**
 *  Start analysis in the app. Call it in your app delegate.
 *  @param azotAppToken is the token generated by Azot for the developer to track his app.
 *  @param video default at YES, set to NO if you don't want video.
 *  @param autoTracking default at YES, set to NO if you don't want auto tracked pages.
 *  @param confidentiality define the confidentiality level of both screenshot and video.
 *  @return void
 */
+ (void)start:(NSString*)azotAppToken video:(bool)video autoTracking:(bool)tracking confidentiality:(AZConfidentiality)confidentialityLevel;

/**
 *  Start analysis of a page. Call it in your controller viewDidAppear. Tips: Use this function to analyse a "page", understood as what the user can see.
 *  @param pageId is the name you'll give to your page. It is the name we will use to refer to your page in your analysis dashboard.
 *  @return void
 */
+ (void)startPage: (NSString*)pageId;

/**
 *  Stop a page analysis. Call it in your controller viewDidDisapear.
 *  @param pageId must be the name you gave to the page you've opened in viewDidAppear with function trackPage.
 *  @return void
 */
+ (void)stopPage: (NSString*)pageId;

/**
 *  Track events you care about in your app.
 *  @param eventId is the name of the event you want to track, can be static or dynamic.
 *  @return void
 */
+ (void)event: (NSString*)eventId;

/**
 *  Used to get feedbacks from the user.
 *  @param message is your user feedback message.
 *  @return void
 */
+ (void)message: (NSString*)message;

/**
 *  Allow you to get your logs if a session ends on a crash, just use AZLog instead of NSLog.
 *  @param format string used to define the log format, same usage as NSLog.
 *  @return void
 */
OBJC_EXTERN void AZLog(NSString *format, ...) NS_FORMAT_FUNCTION(1,2);

/**
 *  Allow you to set the confidentiality level of both video and screenshots.
 *  @param confidentiality is used to define the confidentiality level.
 *  @return void
 */
+ (void)confidentiality: (AZConfidentiality)confidentiality;

/**
 *  Allow you not to use video.
 *  @param video default at YES, set to NO if you don't want video.
 *  @return void
 */
+ (void)video:(bool)video;

@end